import React from 'react';
export const metadata = {
    title: 'Add Product |Dashboard | Next Hero',
    description: 'Generated by create next app',
  }
const AddProduct = () => {
    return (
        <div>
            AddProduct
        </div>
    );
};

export default AddProduct;