import React from 'react';
export const metadata = {
    title: ' About | Next Hero',
    description: 'Generated by create next app',
  }
const aboutPage = () => {
    return (
        <div>
            aboutPage
        </div>
    );
};

export default aboutPage;