import './globals.css'
import { Roboto } from 'next/font/google'

const roboto = Roboto({ subsets: 
  ['latin'],
  weight:['100','400','500'],
  variable:'--font-roboto'
})

export const metadata = {
  title: 'Next Hero',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} font-roboto`}>

        {children}

      </body>
    </html>
  )
}
