import React from 'react';
export const metadata = {
    title: ' Profile | Next Hero',
    description: 'Generated by create next app',
  }
const profilePage = () => {
    return (
        <div>
            profilePage
        </div>
    );
};

export default profilePage;