// "use client"

// import { useRouter } from 'next/navigation';
import Link from 'next/link';
import React from 'react';
import LoadBlogsData from '../utils/LoadBlogsData';
// const blogItems = [
//     {
//         id: '1',
//         year: '2023',
//         title: 'title-1'

//     },
//     {
//         id: '2',
//         year: '2023',
//         title: 'title-2'

//     },
//     {
//         id: '3',
//         year: '2023',
//         title: 'title-3'

//     },
//     {
//         id: '4',
//         year: '2023',
//         title: 'title-4'

//     },
// ]
export const metadata = {
    title: 'Blog | Next Hero',
    description: 'Generated by create next app',
  }
  
const BlogsPage = async () => {
const blogs = await LoadBlogsData()
    // const router = useRouter()




    return (
        <div className='container mx-auto'>
            {blogs.map(({ id, body, title }) =>

                <div key={id} className='block border border-orange-500 p-2 my-4'>
                    <h2 className='text-2xl'>{id}-- {title}</h2>
                    <p>
                        {body}
                    </p>
                    <Link
                        // href={{
                        //     pathname: `/blog/${year}/${id}`,
                        //     query: {
                        //         title: title
                        //     }
                        // }}
                        href={`/blog/${id}`}
                    // onClick={()=>router.push(`/blog/${year}/${id}?title=${title}`)}
                    >
                          <button className='bg-blue-600 py-2 p-2 mt-2 rounded-lg'>Details</button>

                    </Link>
                </div>

            )}
        </div>
    );
};

export default BlogsPage;